/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package msaccessdiffandsqlscripter;

import java.io.File;
import java.io.IOException;
import java.util.logging.FileHandler;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.LogManager;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JFileChooser;

class MSAccesFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".accdb") || file.getAbsolutePath().endsWith(".mdb") ;
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Acces Databases (*.mdb, *.accdb)";
        }
    } 


/**
 *
 * @author Vincent Kool
 */
public class GUI extends javax.swing.JFrame {
private MSAccessDiffAndSQLScripter main;
private String oldDBLocation, newDBLocation;
private Thread scripterThread;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfcOLD = new javax.swing.JFileChooser();
        jfcNEW = new javax.swing.JFileChooser();
        jlblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlblOldDB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfOldLoc = new javax.swing.JTextField();
        jtfNewLoc = new javax.swing.JTextField();
        jbtnBrowseOld = new javax.swing.JButton();
        jbtnBrowseNew = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jpbProgress = new javax.swing.JProgressBar();
        jbtnStart = new javax.swing.JButton();
        jCancelBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jfcOLD.setDialogTitle("OLD MS Acces Database File");
        jfcOLD.setFileFilter(new MSAccesFilter());

        jfcNEW.setFileFilter(new MSAccesFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weaponsystems.net");

        jlblTitle.setFont(jlblTitle.getFont().deriveFont(jlblTitle.getFont().getStyle() | java.awt.Font.BOLD, jlblTitle.getFont().getSize()+5));
        jlblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitle.setText("Convert MS Acces changes to MySQL Script");

        jlblOldDB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblOldDB.setText("old MS Access database:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("new MS Access database:");

        jtfOldLoc.setEditable(false);
        jtfOldLoc.setFocusable(false);

        jtfNewLoc.setEditable(false);
        jtfNewLoc.setFocusable(false);

        jbtnBrowseOld.setText("Browse");
        jbtnBrowseOld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseOldActionPerformed(evt);
            }
        });

        jbtnBrowseNew.setText("Browse");
        jbtnBrowseNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseNewActionPerformed(evt);
            }
        });

        jbtnStart.setText("Start");
        jbtnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStartActionPerformed(evt);
            }
        });

        jCancelBtn.setText("Cancel");
        jCancelBtn.setEnabled(false);
        jCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelBtnActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jlblOldDB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfOldLoc)
                            .addComponent(jtfNewLoc, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnBrowseOld)
                            .addComponent(jbtnBrowseNew))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpbProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCancelBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnStart)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblOldDB)
                    .addComponent(jtfOldLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBrowseOld))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNewLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBrowseNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpbProgress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnStart)
                        .addComponent(jCancelBtn)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBrowseOldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseOldActionPerformed
        int returnVal = jfcOLD.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jfcOLD.getSelectedFile();
            oldDBLocation = file.getAbsolutePath();
            jtfOldLoc.setText(oldDBLocation);
        } else {
            Logger.getLogger("net.weaponsystems.SQLScripter").fine("File access cancelled by user.");
        }
    }//GEN-LAST:event_jbtnBrowseOldActionPerformed

    private void jbtnBrowseNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseNewActionPerformed
        int returnVal = jfcNEW.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jfcNEW.getSelectedFile();
            newDBLocation = file.getAbsolutePath();
            jtfNewLoc.setText(newDBLocation);
        } else {
            Logger.getLogger("net.weaponsystems.SQLScripter").fine("File access cancelled by user.");
        }
    }//GEN-LAST:event_jbtnBrowseNewActionPerformed

    private void jbtnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStartActionPerformed
    // Check for old and new locations
        if(!(   (oldDBLocation != null) &&
                (newDBLocation != null) &&
                (!oldDBLocation.isEmpty()) &&
                (!newDBLocation.isEmpty()))) {
            jTextArea1.setText("First choose two database files");
        } else {
            main = new MSAccessDiffAndSQLScripter(oldDBLocation, newDBLocation, this);
            scripterThread = new Thread(main);
            jbtnStart.setEnabled(false);
            jCancelBtn.setEnabled(true);
            scripterThread.start();
            
        }
    // Initialize scripter
    }//GEN-LAST:event_jbtnStartActionPerformed

    private void jCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelBtnActionPerformed
        if(scripterThread != null){
            scripterThread.interrupt();
            jbtnStart.setEnabled(true);
            jCancelBtn.setEnabled(false);
        }
            
    }//GEN-LAST:event_jCancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set a logger */
        //<editor-fold defaultstate="collapsed" desc=" Set a logger ">
        if(System.getProperty("java.util.logging.config.class") == null
                && System.getProperty("java.util.logging.config.file") == null)
        {
            try
            {
                LogManager.getLogManager().reset();

                Logger logger = Logger.getLogger("net.weaponsystems.SQLScripter");
                logger.setLevel(Level.ALL);
                logger.setUseParentHandlers(false);
                final int LOG_ROTATION_COUNT = 10;
                Handler handler = new FileHandler("%h/WeaponsystemsScripter.log", 0, LOG_ROTATION_COUNT);
                handler.setLevel(Level.ALL);
                handler.setFormatter(new java.util.logging.SimpleFormatter());
                logger.addHandler(handler);
            }
            catch (IOException e)
            {
                Logger.getLogger("net.weaponsystems.SQLScripter").log(Level.SEVERE, "Can't create log file handler", e);
            }
        }
        
        //</editor-fold>
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                Handler WindowHandler = new WindowHandler();
//                WindowHandler.setLevel(Level.INFO);
//                Logger.getLogger("net.weaponsystems.SQLScripter").addHandler(WindowHandler);
                
                new GUI().setVisible(true);
            }   
        });
    }
    
    public void updateStatusBarAndTextArea(float value, String message){
        float val = jpbProgress.getMaximum()*value;
        jpbProgress.setValue((int) Math.rint(Math.ceil(val)));
        jTextArea1.append(message+"\n");
        //this.update(jpbProgress.getGraphics());
        if(value == 1.0)
        {
            jbtnStart.setEnabled(true);
            jCancelBtn.setEnabled(false);
        }
        //this.getGraphics()
    }
        
    public void updateStatusBar(float value){
        float val = jpbProgress.getMaximum()*value;
        jpbProgress.setValue((int) Math.rint(Math.ceil(val)));
        //this.update(jpbProgress.getGraphics());
        if(value == 1.0)
        {
            jbtnStart.setEnabled(true);
            jCancelBtn.setEnabled(false);
        }
        //this.getGraphics()
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbtnBrowseNew;
    private javax.swing.JButton jbtnBrowseOld;
    private javax.swing.JButton jbtnStart;
    private javax.swing.JFileChooser jfcNEW;
    private javax.swing.JFileChooser jfcOLD;
    private javax.swing.JLabel jlblOldDB;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JProgressBar jpbProgress;
    private javax.swing.JTextField jtfNewLoc;
    private javax.swing.JTextField jtfOldLoc;
    // End of variables declaration//GEN-END:variables
}
